POST http://localhost:8080/auth
content-type: application/json

{
    "login": "testuser232",
    "password": "tesert",
    "isAdmin" : true
}

# "testuser232"
# "tesert"

# "testuser1mailcom"
# "test"